@extends('layouts.card')

@section('title', 'Two-Factor Authentication')

@section('card')
  <div class="max-w-md w-full bg-white dark:bg-dark-900 rounded-3xl shadow-xl border border-slate-200/80 dark:border-dark-800 p-8 sm:p-10 space-y-6"
       x-data="{ recovery: false }">
    <div class="text-center">
      <div class="w-12 h-12 rounded-2xl bg-brand-50 text-brand-600 dark:bg-brand-950/60 dark:text-brand-400 flex items-center justify-center mx-auto mb-4">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path></svg>
      </div>
      <h1 class="text-2xl font-extrabold text-slate-900 dark:text-white">Two-Factor Authentication</h1>
      <p class="text-xs text-slate-500 dark:text-dark-400 mt-2" x-show="!recovery">Enter the 6-digit verification code generated by your Authenticator app.</p>
      <p class="text-xs text-slate-500 dark:text-dark-400 mt-2" x-show="recovery" x-cloak>Enter one of your emergency recovery codes.</p>
    </div>

    @error('code') <p class="text-center text-xs text-rose-500 font-semibold">{{ $message }}</p> @enderror
    @error('recovery_code') <p class="text-center text-xs text-rose-500 font-semibold">{{ $message }}</p> @enderror

    <form method="POST" action="{{ route('two-factor.login') }}" class="space-y-6">
      @csrf

      {{-- OTP input: six boxes writing into a hidden combined field --}}
      <div x-show="!recovery" x-data="otpInput()" class="flex items-center justify-center gap-2 sm:gap-3">
        <template x-for="(d, i) in digits" :key="i">
          <input type="text" inputmode="numeric" maxlength="1"
                 x-model="digits[i]"
                 x-on:input="onInput(i, $event)"
                 x-on:keydown.backspace="onBackspace(i, $event)"
                 x-on:paste.prevent="onPaste($event)"
                 :x-ref="'box' + i"
                 class="w-11 h-12 text-center text-lg font-bold rounded-xl bg-slate-50 dark:bg-dark-800 border border-slate-200 dark:border-dark-700 focus:outline-none focus:ring-2 focus:ring-brand-500">
        </template>
        <input type="hidden" name="code" x-model="combined">
      </div>

      <div x-show="recovery" x-cloak>
        <input type="text" name="recovery_code" placeholder="e.g. xj4k2-9dm1p"
               class="w-full px-3.5 py-2.5 text-center text-xs rounded-xl bg-slate-50 dark:bg-dark-800 border border-slate-200 dark:border-dark-700 focus:outline-none focus:ring-2 focus:ring-brand-500">
      </div>

      <button type="submit" class="w-full py-3 rounded-xl bg-brand-600 hover:bg-brand-700 text-white font-bold text-xs shadow-md shadow-brand-500/25 transition-all">
        Verify &amp; Continue &rarr;
      </button>
    </form>

    <div class="text-center text-xs text-slate-400 space-y-2">
      <p x-show="!recovery">Didn't receive a prompt? <button type="button" x-on:click="recovery = true" class="text-brand-600 dark:text-brand-400 font-bold hover:underline">Use backup recovery code</button></p>
      <p x-show="recovery" x-cloak><button type="button" x-on:click="recovery = false" class="text-brand-600 dark:text-brand-400 font-bold hover:underline">Use authenticator code instead</button></p>
      <div><a href="{{ route('login') }}" class="hover:underline">&larr; Return to Sign In</a></div>
    </div>
  </div>
@endsection
